### ISSUE TITLE
Feature request: OAuth support (OpenID Connect and/or SAML)

### ISSUE THREAD

**Issue by samip5** [TomBursch/kitchenowl#212] opened 2023-08-02 11:08 UTC
### What's the feature 🧐

I would love to be able to use OAuth with Authentik or Authelia (OpenID Connect or SAML).

### Extra information and references

- I'm using Kubernetes at home, and I really would love to not have separate users for all the things. :=)
- Flask and OAuth should be simple ish to do. https://flask-oidc.readthedocs.io/en/latest/

**Comment by samip5** [comment] 2023-08-02 11:12
This may be a duplicate of https://github.com/TomBursch/kitchenowl/issues/32 but I'm not sure as I tried searching but with my keywords didn't find it before creating this one.

**Comment by TomBursch** [comment] 2023-08-02 12:21
No worries, but I will close this as a duplicate of #32

**Closed as not planned by TomBursch** 2023-08-02 12:21 UTC
Labels: duplicate, enhancement
