### ISSUE TITLE
Feature request: Ability to alter base application path in the URL.

### ISSUE THREAD

**Issue by Fen-nix** [TomBursch/kitchenowl#237] opened 2023-09-05 01:42 UTC
### What's the feature 🧐

There are a number of places (notably main.dart.js) that seem to force the application to live on the root of the webserver (/) and it would be nice to have the ability to let it live at `/ko`.

Setting `FRONT_URL` and then modifying the `<base href="">` tag works for a number of the requests but fails to let the web app run due to the way api_service.dart (or one of its dependent functions) builds the API path. The result is that the API is always assumed to live at `/api`. I suspect the issue stems from the way the URL is determined in `setup()` in `lib/cubits/auth_cubit.dart` but I am not certain.

It would be useful to have a separate `BASE_URL` or similar environment variable and adjust other paths accordingly.

**Comment by TomBursch** [comment] 2023-09-05 10:33
I will close this as a duplicate of #130. Thanks for the issue nonetheless! Yes, the frontend just assumes whatever URL you typed in + `/api` is where it tries to connect to the backend.

**Closed as completed by TomBursch** 2023-09-05 10:33 UTC
Labels: enhancement
