### ISSUE TITLE
Feature request: add pictures to a shopping item

### ISSUE THREAD

**Issue by preambule** [TomBursch/kitchenowl#339] opened 2023-12-24 11:52 UTC
### What's the feature 🧐

When we add or edit an item in the shopping list, have the possibility to add a picture from our album or take one now. This can help when we want a specific product and are so helpful when it's a another person who do the purchase.

### Extra information and references

- You just have to take the picture section like when we add a expense in the budget section.

**Comment by TomBursch** [comment] 2023-12-24 12:57
Duplicate of #123

**Closed as not planned by TomBursch** 2023-12-24 12:57 UTC
Labels: duplicate, enhancement
