### ISSUE TITLE
Bug: No Option to Sign-Up in Self Hosted

### ISSUE THREAD

**Issue by Dizzy49** [TomBursch/kitchenowl#254] opened 2023-10-03 15:04 UTC
### Is this urgent?

Yes

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

v6.0.5

### What's the problem 🤔

Installed v6.0.5 on TrueNAS Scale and there is no option to Sign Up.  There does not appear to be a default user/pass so the app is essentially useless as there is no way to access it.

**Comment by TomBursch** [comment] 2023-10-03 16:05
I'm not maintaining the TrueNAS app, can you share some logs? It works for a fresh install on docker. You should be greeted with this screen on a new install:
![image](https://github.com/TomBursch/kitchenowl/assets/9092682/76862629-2869-496d-9612-9f13998083f2)

Until we have found a solution I will update the server management script so you can create a user there (https://docs.kitchenowl.org/reference/management/).

**Comment by Dizzy49** [comment] 2023-10-03 20:00
This was opened about the same time I was having issue.  lots of info
including logs:
https://github.com/truecharts/charts/issues/13049

Thanks!

**Comment by TomBursch** [comment] 2023-10-03 20:40
Thanks for the info! Could be related to #252. I just published a new version that fixed that. Can you confirm that you still have this issue?
Edit: looking through the logs further, this is caused by the issue I linked and should be fixed now.

**Comment by Dizzy49** [comment] 2023-10-05 07:12
It is working now, thank you!

**Comment by TomBursch** [comment] 2023-10-05 08:38
Great!

**Closed as completed by TomBursch** 2023-10-05 08:38 UTC
Labels: bug
