### ISSUE TITLE
Feature request: Integrate barcode scanner with API calls to Open Food Facts

### ISSUE THREAD

**Issue by hillbicks** [TomBursch/kitchenowl#122] opened 2023-01-12 22:09 UTC
### What's the feature 🧐

Hey Tom,

let me begin by saying: I know this is a big feature request, but I really like the idea so I wanted to share. 

What if there was an option in kitchenowl to add items via barcode scanner which then pulls the product details and photo from open food facts. Integrate the information retrieved into a new product within kitchenowl. 

[The Barcode Scanner](https://gitlab.com/Atharok/BarcodeScanner) app has this functionality and is released under GPL3. 

They also have
- Cosmetic Products with [Open Beauty Facts](https://world.openbeautyfacts.org/)
- Pet Food Products with [Open Pet Food Facts](https://world.openpetfoodfacts.org/)
- Books with [Open Library](https://openlibrary.org/)

integrated. Don't think books would be necessary, but the cosmetic and pet food products would be a nice touch too. 

My use case for this would be: A product is empty and before throwing the packaging away, I'll open kitchenowl, press the + icon in the lower corner and a barcode scanner is opened. I scan the barcode of the empty product and kitchenowl pulls the details of the scanned product and adds it to the "to buy" list. 

Like I said, a big feature request but I thought I share the thought. :)

### Extra information and references

![image](https://user-images.githubusercontent.com/3480073/212192133-48b9d5b4-addc-4c4a-825b-00cd01d9ef56.png)

**Comment by TomBursch** [comment] 2023-01-26 17:46
Thanks for the feature request! I'll close this as this is a duplicate of #74 and add your great description to the other issue.

**Closed as not planned by TomBursch** 2023-01-26 17:46 UTC
Labels: duplicate, enhancement
